name: Deploy to the Production Environment

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install the twilio-run Toolkit
      run: npm install --save-dev twilio-run

    - name: Deploy Application
      run: npm run deploy:prod
      env:
        AUTHORIZED_BROADCAST_PHONE_NUMBERS: ${{ secrets.AUTHORIZED_BROADCAST_PHONE_NUMBERS }}
        NOTIFY_SERVICE_SID: ${{ secrets.NOTIFY_SERVICE_SID }}
        SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
